version: '3.9'

services:
  node:
    container_name: node
    tty: true
    build: ./build/docker/node
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    environment:
      - HOST=0.0.0.0